<?php

return [
    [
        "user_id" => 1,
        "name" => "John Michael",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/JD.jpg",
        "performance" => "",
        "promotions" => [3],
        "specializations" => [23],
    ],
    [
        "user_id" => 2,
        "name" => "Gregory",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Dr-House.jpg",
        "performance" => "",
        "promotions" => [3],
        "specializations" => [16, 17, 18],
    ],
    [
        "user_id" => 3,
        "name" => "James",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/James-WIlson.jpg",
        "performance" => "",
        "promotions" => [2],
        "specializations" => [19],
    ],
    [
        "user_id" => 4,
        "name" => "Eric",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Eric-Foreman.jpeg",
        "performance" => "",
        "promotions" => [1],
        "specializations" => [16, 20],
    ],
    [
        "user_id" => 5,
        "name" => "Martha",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Masters.jpeg",
        "performance" => "",
        "promotions" => [2],
        "specializations" => [16, 14],
    ],
    [
        "user_id" => 6,
        "name" => "Robert",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Robert-Chase.jpg",
        "performance" => "",
        "promotions" => [1],
        "specializations" => [14, 16, 21],
    ],
    [
        "user_id" => 7,
        "name" => "Allison",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Cameron.jpg",
        "performance" => "",
        "promotions" => [2],
        "specializations" => [16, 20],
    ],
    [
        "user_id" => 8,
        "name" => "Tredici",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/13.jpeg",
        "performance" => "",
        "promotions" => [1],
        "specializations" => [16, 23],
    ],
    [
        "user_id" => 9,
        "name" => "Chris",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Taub.jpg",
        "performance" => "",
        "promotions" => [3],
        "specializations" => [16, 22],
    ],
    [
        "user_id" => 10,
        "name" => "Lawrence",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Kutner.jpg",
        "performance" => "",
        "promotions" => [2],
        "specializations" => [2],
    ],
    [
        "user_id" => 11,
        "name" => "Elliot",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Elliot-Reid.jpeg",
        "performance" => "",
        "promotions" => [1],
        "specializations" => [4, 15],
    ],
    [
        "user_id" => 12,
        "name" => "Christopher Duncan",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Christopher-Duncan-Turk.jpg",
        "performance" => "",
        "promotions" => [3],
        "specializations" => [14, 1],
    ],
    [
        "user_id" => 13,
        "name" => "Percival Ulysses",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Cox.jpg",
        "performance" => "",
        "promotions" => [2],
        "specializations" => [15, 7],
    ],
    [
        "user_id" => 14,
        "name" => "Robert-Kelso",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Robert-Kelso.jpg",
        "performance" => "",
        "promotions" => [3],
        "specializations" => [10, 17],
    ],
    [
        "user_id" => 15,
        "name" => "Todd",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Tood.jpg",
        "performance" => "",
        "promotions" => [2],
        "specializations" => [10, 13, 17],
    ],

];
