<?php

return [
    [
        "email" => "j.d@mail.com",
        "password" => "11111111",
        "name" => "John Michael",
        "lastname" => "Dorian",
        "address" => "Via numero 1 - Città 1",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "gregoryhouseisthebest@mail.com",
        "password" => "22222222",
        "name" => "Gregory",
        "lastname" => "House",
        "address" => "Via numero 2 - Città 2",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "J.Wilson@mail.com",
        "password" => "33333333",
        "name" => "James",
        "lastname" => "Wilson",
        "address" => "Via numero 3 - Città 3",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "eric.foreman@mail.com",
        "password" => "44444444",
        "name" => "Eric",
        "lastname" => "Foreman",
        "address" => "Via numero 4 - Città 4",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "babbo.natale@mail.com",
        "password" => "55555555",
        "name" => "Babbo",
        "lastname" => "Natale",
        "address" => "Via numero 5 - Città 5",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "robert.chase.@mail.com",
        "password" => "66666666",
        "name" => "Robert",
        "lastname" => "Chase",
        "address" => "Via numero 6 - Città 6",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "allison.cameron@mail.com",
        "password" => "77777777",
        "name" => "Allison",
        "lastname" => "Cameron",
        "address" => "Via numero 7 - Città 7",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "remy.hadley@mail.com",
        "password" => "88888888",
        "name" => "Remy",
        "lastname" => "Hadley",
        "address" => "Via numero 8 - Città 8",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "chris.taub @mail.com",
        "password" => "99999999",
        "name" => "Chris",
        "lastname" => "Taub",
        "address" => "Via numero 9 - Città 9",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "l.kutner@mail.com",
        "password" => "00000000",
        "name" => "Lawrence",
        "lastname" => "Kutner",
        "address" => "Via numero 10 - Città 10",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "elliot.reid@mail.com",
        "password" => "11222222",
        "name" => "Elliot",
        "lastname" => "Reid",
        "address" => "Via numero 11 - Città 11",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "christopher.turk@mail.com",
        "password" => "12222222",
        "name" => "Christopher Duncan",
        "lastname" => "Turk",
        "address" => "Via numero 12 - Città 12",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "perry.cox@mail.com",
        "password" => "13222222",
        "name" => "Percival Ulysses",
        "lastname" => "Cox",
        "address" => "Via numero 13 - Città 13",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "Bob.Kelso.@mail.com",
        "password" => "14222222",
        "name" => "Robert",
        "lastname" => "Kelso",
        "address" => "Via numero 14 - Città 14",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
    [
        "email" => "iltodd@mail.com",
        "password" => "15222222",
        "name" => "Todd",
        "lastname" => "Quinlan",
        "address" => "Via numero 15 - Città 15",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion" => "",
    ],
];
