<?php

return [
    [
        "email" => "pinco.pallino@mail.com",
        "password" => "111112",
        "name" => "Pinco",
        "lastname" => "Pallino",
        "address" => "Via numero 1 - Città 1",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion_counter" => "",
        "promotions" => [2],
    ],
    [
        "email" => "franco.pallino@mail.com",
        "password" => "222223",
        "name" => "Franco",
        "lastname" => "Pallino",
        "address" => "Via numero 2 - Città 2",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion_counter" => "",
        "promotions" => [2],
    ],
    [
        "email" => "pasquale.pallino@mail.com",
        "password" => "333334",
        "name" => "Pasquale",
        "lastname" => "Pallino",
        "address" => "Via numero 3 - Città 3",
        "telephone" => "1234567890",
        "curriculum-vitae" => "",
        "image" => "",
        "performance" => "",
        "promotion_counter" => "",
        "promotions" => [3],
    ],
//     [
//         "email" => "rudolf.natale@mail.com",
//         "password" => "333334",
//         "name" => "Franco",
//         "lastname" => "Pallino",
//         "address" => "Via numero 4 - Città 4",
//         "telephone" => "1234567890",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "babbo.natale@mail.com",
//         "password" => "444445",
//         "name" => "Babbo",
//         "lastname" => "Natale",
//         "address" => "Via numero 5 - Città 5",
//         "telephone" => "1234567890",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "giulio.anselmo@mail.com",
//         "password" => "555556",
//         "name" => "Giulio",
//         "lastname" => "Anselmo",
//         "address" => "Via numero 6 - Città 6",
//         "telephone" => "1234567890",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "giulio.anselmo@mail.com",
//         "password" => "666667",
//         "name" => "Paolo",
//         "lastname" => "Anselmo",
//         "address" => "Via numero 7 - Città 7",
//         "telephone" => "1234567890",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "radolfo.raduken@mail.com",
//         "password" => "777778",
//         "name" => "Radolfo",
//         "lastname" => "Raduken",
//         "address" => "Via numero 8 - Città 8",
//         "telephone" => "1234567890",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "jason.salmon@mail.com",
//         "password" => "888889",
//         "name" => "Jason",
//         "lastname" => "Salmon",
//         "address" => "Via numero 9 - Città 9",
//         "telephone" => "1234567890",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "guglielmo.blue@mail.com",
//         "password" => "9999910",
//         "name" => "Guglielmo",
//         "lastname" => "Blue",
//         "address" => "Via numero 10 - Città 10",
//         "telephone" => "1234567890",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "francesco.deiana@gmail.com",
//         "password" => "abcd11",
//         "name" => "Francesco",
//         "lastname" =>"Deiana",
//         "address" => "Via numero 11 - Città 11",
//         "telephone" => "3342623655",
//         "curriculum vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "paolo.bianchi@gmail.com",
//         "password" => "abcd12",
//         "name" => "Paolo",
//         "lastname" =>"Bianchi",
//         "address" => "Via numero 12 - Città 12",
//         "telephone" => "3282673655",
//         "curriculum vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "mario.rossi@gmail.com",
//         "password" => "abcd13",
//         "name" => "Paolo",
//         "lastname" =>"Bianchi",
//         "address" => "Via numero 13 - Città 13",
//         "telephone" => "3472673655",
//         "curriculum vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "roberta.verdi@gmail.com",
//         "password" => "abcd14",
//         "name" => "Roberta",
//         "lastname" =>"Verdi",
//         "address" => "Via numero 14 - Città 14",
//         "telephone" => "3472888655",
//         "curriculum vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "rosa.rossi@gmail.com",
//         "password" => "abcd15",
//         "name" => "Rosa",
//         "lastname" =>"Rossi",
//         "address" => "Via numero 15 - Città 15",
//         "telephone" => "3462673232",
//         "curriculum vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "maurizio.carboni@gmail.com",
//         "password" => "abcd16",
//         "name" => "Maurizio",
//         "lastname" =>"Carboni",
//         "address" => "Via numero 16 - Città 16 ",
//         "telephone" => "3282673011",
//         "curriculum vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "marcello.bianchi@gmail.com",
//         "password" => "abcd17",
//         "name" => "Marcello",
//         "lastname" =>"Bianchi",
//         "address" => "Via numero 17 - Città 17",
//         "telephone" => "3411113655",
//         "curriculum vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "alessandra.rossi@gmail.com",
//         "password" => "abcd18",
//         "name" => "Alessandra",
//         "lastname" =>"Rossi",
//         "address" => "Via numero 18 - Città 18",
//         "telephone" => "3452673005",
//         "curriculum vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "enrico.verdi@gmail.com",
//         "password" => "abcd19",
//         "name" => "Enrico",
//         "lastname" =>"Verdi",
//         "address" => "Via numero 19 - Città 19",
//         "telephone" => "3408275999",
//         "curriculum vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "rossella.rossi@gmail.com",
//         "password" => "abcd20",
//         "name" => "Rossella",
//         "lastname" =>"Rossi",
//         "address" => "Via numero 20 - Città 20",
//         "telephone" => "3478900212",
//         "curriculum vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],
//     [
//         "email" => "G.cappello@mail.com",
//         "password" => "13121312",
//         "name" => "Giorgio",
//         "lastname" => "Cappello",
//         "address" => "Via Roma - Roma",
//         "telephone" => "3312972998",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],

//     [
//         "email" => "MarcoGambero@mail.com",
//         "password" => "0109020803",
//         "name" => "Marco",
//         "lastname" => "Gambero",
//         "address" => "Via Latina - Firenze",
//         "telephone" => "3112372394",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],

//     [
//         "email" => "docOrenzo@mail.com",
//         "password" => "4232112L",
//         "name" => "Luca",
//         "lastname" => "Orenzo",
//         "address" => "Via Sales - Genova",
//         "telephone" => "3335467823",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],

//     [
//         "email" => "TrottolaDoc@mail.com",
//         "password" => "1009981AA",
//         "name" => "Gigi",
//         "lastname" => "La Trottola",
//         "address" => "Via Sales - Genova",
//         "telephone" => "3335467823",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],

//     [
//         "email" => "LolloLacustre@mail.com",
//         "password" => "as1312",
//         "name" => "Lollo",
//         "lastname" => "Lacustre",
//         "address" => "Via Ritorno - Venezia",
//         "telephone" => "3335467823",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],

//     [
//         "email" => "Tmblurr@mail.com",
//         "password" => "Roma1996",
//         "name" => "Gianmarco",
//         "lastname" => "Tocco",
//         "address" => "Via Massimo - Frosinone",
//         "telephone" => "3342743876",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],

//     [
//         "email" => "therealmarza@mail.com",
//         "password" => "Trmn100",
//         "name" => "Francesco",
//         "lastname" => "Marzano",
//         "address" => "Via Lucca - Lucca",
//         "telephone" => "3334567889",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],

//     [
//         "email" => "PeffoD@mail.com",
//         "password" => "QWERTY123",
//         "name" => "Dario",
//         "lastname" => "Moccia",
//         "address" => "Via Ortolano - Brindisi",
//         "telephone" => "3356789432",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],

//     [
//         "email" => "asdcoder@mail.com",
//         "password" => "Lol4567",
//         "name" => "Marco",
//         "lastname" => "Merrino",
//         "address" => "Via Pizza - Bari",
//         "telephone" => "3335742823",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],

//     [
//         "email" => "DottorGucci@mail.com",
//         "password" => "13121312",
//         "name" => "Stefano",
//         "lastname" => "Gucci",
//         "address" => "Via Sales - Genova",
//         "telephone" => "3333461813",
//         "curriculum-vitae" => "",
//         "image" => "",
//         "performance" => "",
//         "promotion" => "",
//         "promotion_counter" => "",
//     ],

];